site_name: Stripe Mock API Docs
site_description: Comprehensive API reference and developer documentation for a Stripe-inspired payment platform.
site_url: https://atharkharal.github.io/stripe-mock-api-docs/
repo_url: https://github.com/atharkharal/stripe-mock-api-docs
repo_name: GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  font:
    text: Roboto
    code: Fira Code
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.tooltips
    - toc.integrate
    - header.autohide
    - footer.social

nav:
  - Overview: index.md
  - Guides:
      - Creating a Charge: guides/creating-a-charge.md
  - Reference:
      - Authentication: reference/authentication.md
      - Error Codes: reference/errors.md
  - Webhooks:
      - Handling Events: webhooks/handling-events.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.magiclink
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - awesome-pages
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AtharKharal
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/AtharKharal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle
  
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark

analytics:
  provider: google
  property: G-XXXXXXXXXX

extra_css:
  - styles/extra.css

extra_javascript:
  - js/extra.js

copyright: Copyright &copy; 2025 Athar Kharal. All rights reserved.